data <- read.table("household_power_consumption.txt", skip = 66637, nrow = 2880,col.names = colnames(read.table("household_power_consumption.txt", nrow = 2,header = TRUE,sep =";")),sep=";")
data$Date <- strptime(paste(data$Date,data$Time), "%d/%m/%Y %H:%M:%S")
png(filename = "plot4.png",width = 480, height = 480, units = "px")
par(mfrow = c(2, 2))
with(data,
{plot(data$Date,data$Global_active_power,type="l",ylab = "Global Active Power",xlab="",main="")
plot(data$Date,data$Voltage,type="l",ylab = "Voltage",xlab="datetime",main="")
plot(data$Date,data$Sub_metering_1,type="l",ylab = "Energy sub metering",xlab="",main="")
lines(data$Date,data$Sub_metering_2,col="red")
lines(data$Date,data$Sub_metering_3,col="blue")
legend("topright",bty = "n",lty = c(1, 1, 1),lwd = 2, cex = 1,col = c("black", "red","blue"),legend = c("Sub_metering_1","Sub_metering_2", "Sub_metering_3"))
plot(data$Date,data$Global_reactive_power,type="l",ylab = "Global_reactive_power",xlab="datetime",main="")})
dev.off()