data <- read.table("household_power_consumption.txt", skip = 66637, nrow = 2880,col.names = colnames(read.table("household_power_consumption.txt", nrow = 2,header = TRUE,sep =";")),sep=";")
data$Date <- strptime(paste(data$Date,data$Time), "%d/%m/%Y %H:%M:%S")
png(filename = "plot3.png",width = 480, height = 480, units = "px")
plot(data$Date,data$Sub_metering_1,type="l",ylab = "Energy sub metering",xlab="",main="")
lines(data$Date,data$Sub_metering_2,col="red")
lines(data$Date,data$Sub_metering_3,col="blue")
legend("topright",lty = c(1, 1, 1),lwd = 2, cex = 1.2,col = c("black", "red","blue"),legend = c("Sub_metering_1","Sub_metering_2", "Sub_metering_3"))
dev.off()
